version: '3'

services:
  gradetracker:
    image: chtka/gradetracker
    ports:
      - "8000:8000"
    volumes:
      - ./:/gradetracker/
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/
    
  