version: '3'

services:
  gradetracker:
    ports:
      - "8000:8000"
    build: .
    volumes:
      - ./:/src
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/
    
  