# Generated by Django 2.0.7 on 2018-08-07 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('weight', models.FloatField(default=0)),
                ('weight_alternate', models.FloatField(default=0)),
                ('points_earned', models.FloatField(default=0)),
                ('points_total', models.FloatField(default=0)),
                ('grade', models.FloatField(default=100)),
                ('num_drops_allowed', models.IntegerField(default=0)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
            ],
        ),
    ]
