# Generated by Django 2.0.7 on 2018-07-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=45)),
                ('number', models.CharField(max_length=45)),
                ('verbose_name', models.CharField(default='', max_length=254)),
                ('institution', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
